import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning
				className={`
          ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="fixed top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[linear-gradient(354.0938588862295deg,_#f3f6de_13%,_#dd8d72_94%)]"></div>
				{children}
				<Toaster />
			</body>
		</html>
	);
}
